
steps:
  # run from the start
  # this will decrypt the encrypted file and secret
  - id: 'prepare-secret'
    name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['-']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --project=${PROJECT_ID} --secret=staging-demo-gcp --format='get(payload.data)' | tr '_-' '/+' | base64 -d > ./.env
  - id: 'build-app-image'
    name: 'gcr.io/kaniko-project/executor:latest'
    waitFor: ['prepare-secret']
    args:
      - --dockerfile=${_APP_DOCKER_FILE}
      - --destination=gcr.io/${PROJECT_ID}/${_CLOUD_RUN_SERVICE_NAME}:latest
      - --destination=gcr.io/${PROJECT_ID}/${_CLOUD_RUN_SERVICE_NAME}:$TAG_NAME
      - --cache=true
      - --cache-ttl=336h

  # deploy container image to Cloud Run
  - id: 'deploy-app'
    name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['build-app-image']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ${_CLOUD_RUN_SERVICE_NAME} \
          --image gcr.io/$PROJECT_ID/${_CLOUD_RUN_SERVICE_NAME}:$TAG_NAME \
          --allow-unauthenticated \
          --region asia-northeast1 \
          --platform managed \
          --timeout 900 \
          --add-cloudsql-instances ${_CLOUD_SQL_INSTANCES}
substitutions:
  _ENV: staging
  _SECRET_NAME: demo-gcp
  _DECRYPTED_ENV_FILE_LOCATION: ./.env
  _APP_DOCKER_FILE: ./Dockerfile
  _CLOUD_RUN_SERVICE_NAME: demo-gcp
  _CLOUD_SQL_INSTANCES: staging-carparking-jp:asia-northeast1:aplus-staging